/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */
import { alwaysThrows as queryAlwaysThrowsResolver } from "./server";
import { greeting as queryGreetingResolver } from "./server";
import { GraphQLSchema, GraphQLObjectType, GraphQLString } from "graphql";
async function assertNonNull<T>(value: T | Promise<T>): Promise<T> {
    const awaited = await value;
    if (awaited == null)
        throw new Error("Cannot return null for semantically non-nullable field.");
    return awaited;
}
export function getSchema(): GraphQLSchema {
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                alwaysThrows: {
                    name: "alwaysThrows",
                    type: GraphQLString,
                    resolve(source) {
                        return assertNonNull(queryAlwaysThrowsResolver(source));
                    }
                },
                greeting: {
                    name: "greeting",
                    type: GraphQLString,
                    resolve(source) {
                        return assertNonNull(queryGreetingResolver(source));
                    }
                }
            };
        }
    });
    return new GraphQLSchema({
        query: QueryType,
        types: [QueryType]
    });
}
